### ISSUE TITLE
Remove fte_off_edify.sql

### ISSUE THREAD

**Issue by andreabr-dixie** [dsu-effectiveness/utDataStoR#25]
We need to remove fte_off_edify.sql; the sql is not right. It is pulling from student_term_level, but should be pulling from student_section (the query needs to pull section level data not student level data).

**Comment by MattNickodemus** [comment]
Why?

**Comment by andreabr-dixie** [comment]
We need to remove it because the sql is incorrect. The sql is pulling from the wrong table. When doing fte, the graduate and undergraduate data should come from the course (not the student). This sql is pulling from the student (not the course).

**Comment by andreabr-dixie** [comment]
Rewrite to pull so it so it can be joined to the groups data - see the other issue.

**Comment by andreabr-dixie** [comment]
Made a note so that it can be removed when it moves to ut-effectiveness.
