### ISSUE TITLE
Changes to the FTE vignette.

### ISSUE THREAD

**Issue by andreabr-dixie** [dsu-effectiveness/utDataStoR#29]
https://github.com/dsu-effectiveness/utDataStoR/blob/56f21b81a54adb463c3bc060b8f3025439dcd6b1/vignettes/full_time_equivalent.Rmd#L23

I'd like to change the description of FTE to:
Full-Time Equivalent (FTE) is the number of students the university would have if all students were attending full-time. It is calculated on course level student credit hours.

I'd like to change the description for Undergraduate to:
FTE for undergraduate students takes the total undergraduate student credit hours and divides it by 15 credit hours.

I'd like to change the description for Graduate to:
FTE for graduate students takes the total graduate student credit hours and divides it by 10 credit hours.

**Comment by JoyBaule** [comment]
I think this makes sense/works well and this is change we should make on these definitions.

**Comment by andreabr-dixie** [comment]
I made the change in my branch (andrea_20240426) of utDataStoR. It needs to be merged to main. This can be done after it has been moved to ut-effictiveness.
