### ISSUE TITLE
Term to Term Retention SQL

### ISSUE THREAD

**Issue by JoyBaule** [dsu-effectiveness/utDataStoR#9]
Justin, I was working with the term to term retention query in R today, when I run it and ask it to show retention by college I get a lot of N/A values. For example, Fall 18 returns over 70K null college descriptions. I was looking at the SQL, if I remove is_enrolled from export.student_term_level_version and use it on the join for export.student_term_level_outcome it returns only 30 records that do not have a college description for Fall 18. 

Here is what I have edited the SQL to just using a branch I am working on in the KPI repo:

/*
 Term to term retention
 */
   SELECT a.student_id,
          a.term_id,
          a.is_returned_next_spring,
          a.is_returned_next_fall,
          c.primary_major_desc,
          c.primary_degree_id,
          c.primary_degree_desc,
          d.college_abbrv,
          d.college_desc,
          e.first_name,
          e.last_name,
          e.gender_code,
          e.ipeds_race_ethnicity,
          e.is_veteran,
          e.is_international,
          e.is_athlete,
          e.is_first_generation,
          COALESCE(f.is_exclusion, FALSE) AS is_exclusion,
          COALESCE(f.cohort_start_term_id, 'None') AS cohort_start_term_id,
          COALESCE(f.cohort_desc, 'None') AS cohort_type
     FROM export.student_term_outcome a
LEFT JOIN export.term b
       ON b.term_id = a.term_id
      AND a.is_enrolled --moved is_enrolled to here using student_term_outcome
LEFT JOIN export.student_term_level_version c
       ON c.student_id = a.student_id
      AND c.term_id = a.term_id
      --AND c.is_enrolled
      AND c.is_primary_level
      AND c.is_census_version
LEFT JOIN export.academic_programs d
       ON d.program_id = c.primary_program_id
LEFT JOIN export.student e
       ON e.student_id = a.student_id
LEFT JOIN export.student_term_cohort f
       ON f.student_id = a.student_id
      AND f.cohort_desc IN ('First-Time Freshman', 'Transfer')
    WHERE b.season = 'Fall'
      AND substr(a.term_id, 1, 4)::int >= (SELECT substr(term_id, 1, 4)::int - 5
                                     FROM export.term
                                     WHERE is_current_term)

**Comment by jpfeifer-dsu** [comment]
Joy, you are seeing nulls because those students were not enrolled as of census.  The ones I checked enrolled after census, so we have an end of term record, but not a census record.  Do you only want to report census records or both census and end of term?  There is an is_enrolled_census indicator in the outcomes table which will exclude the end of term students from the outcomes table.

**Comment by JoyBaule** [comment]
This is resolved but here is the history just in case we need to come back to it.
